spring:
  application:
    name: creative-utils

  ai:
    vertex:
      ai:
        gemini:
          project-id: ralph-gde
          location: us-central1
          chat:
            options:
              model: gemini-2.5-pro-preview-05-06
